//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BELLITSupportSystemServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int TicketID { get; set; }
        public string ProjectName { get; set; }
        public int EmployeeID { get; set; }
        public string Description { get; set; }
        public System.DateTime RequestedON { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
